### ISSUE TITLE
Why exactly must ESlint also be installed manually?

### ISSUE THREAD

**Issue by boneskull** [lavrton/easyfront#3]
I don't understand this from the blog post. It's a dependency so it _is_ installed. If your plugins don't support a custom path, perhaps they should. npm v3 will flatten everything anyway...

**Comment by lavrton** [comment]
`eslint` can be part of `easyfront` dependencies. flatten is not required here as `eslint` is not part of frontend code (you don't need it inside bundle).

In my opinion using local version of `eslint` (instead of global) is the best approach.
So we have to install `eslint` manually for good text editors/IDE support. Because popular editors (atom, sublime, webstorm, etc) know how to use local version.

**Comment by boneskull** [comment]
So basically the plugins don't support a custom path? That would be the correct place to address the issue.

**Comment by lavrton** [comment]
`eslint` will be in deps for now to support `npm2`. If we decide that `npm2` support is not required `easlint` dep will be removed.
